### ISSUE TITLE
not listed in latest wabbajack

### ISSUE THREAD

**Issue by rkocour** [Fluffernuttersandwich/Better7D2DbyFNS#1]
downloaded latest wabbajack and 7 days 2 die and better 7d2d are not listed even when selecting show unofficial lists.

**Comment by Fluffernuttersandwich** [comment]
Hi rkocour,

As of midday 22DEC2024 EST, the Wabbajack admins told me there was a problem on the back end of the application and currently my list is down.  

It will be down until they fix it, no ETA.

It's not a fault of the list, they are recompiling code to support the 7D2D game on WJ. 
 
'Sorry for the inconvenience, it's out of my control.

I will post at Guppy's Discord when it's fixed.  

- Fin

**Comment by rkocour** [comment]
Sounds good, just joined the discord, so i'll just check in there later.

**Comment by Fluffernuttersandwich** [comment]
Fixed.  Please let me know if you have any issues.

**Comment by rkocour** [comment]
Seems good. Downloaded fine, launched from MO2. No obvious issues. As a side note, greatly appreciate the move to wabbajack and mo2, vortex was giving me a headache as someone who primarily mods in MO2.

**Comment by Fluffernuttersandwich** [comment]
Yes, I wish I did it sooner.  Frontloading the work for Wabbajack was a bit of a learning curve, but now that the hardest part is done, maintaining/updating this list is easy!  And from the limited feedback I have received, everyone prefers Wabbajack over Vortex for this game/list.
