### ISSUE TITLE
unable to download last file RWG cleaner

### ISSUE THREAD

**Issue by vex72** [Fluffernuttersandwich/Better7D2DbyFNS#2]
Log - 00:23:20.804 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download zZZZz_Better7D2D_RWG_Cleaner.zip-6716-1-4-1734830998.zip (NexusDownloader+State|SevenDaysToDie|6716|24238)

Is there a place I can download this manually? Because the installer fatally fails to download it everytime.

![Capture](https://github.com/user-attachments/assets/248f5afa-fad6-4584-b340-862c887ead01)

**Comment by Fluffernuttersandwich** [comment]
Thank you for letting me know, I just updated the ModList to 1.5, but missed that issue.  NexusMods pulled that mod, so I had to update, but was waiting after Wabbajack came up from unexpected downtime.... then I forgot to pull it from MO2.  so give me 5-10 minutes to update to 1.6
